[package]
name = "physics-balls"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.1", default-features = false }
bevy-terminal-renderer = { path = "../../" }
avian2d = "0.3"
rand = "0.8.5"

# For logging
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"
